### ISSUE TITLE
show milestones related information

### ISSUE THREAD

**Issue by lidix91** [q-rapids/qrapids-dashboard#59]
qrapids-backlog provides the list of milestones, try to integrate this information in the dashboard. 
- [x] Add something in the Strategic Indicators view (concrete area, some non-modal view, something like a post-it) with a message like "<number_of_days> days for the next <milestone_type>:  <milestone_description>
-  [x] Add the info in the strategic indicators form (configuration).  A readonly list/table of <milestone_date>, <milestone_type>, and <milestone_description>
- [x] Create a "testing" restful services retoring some fake data for testing

**Comment by lidix91** [comment]
Information about the service interface at [this wiki page](https://github.com/q-rapids/qrapids-dashboard/wiki/qrapids-backlog-Services)
